### ISSUE TITLE
Hi team

### ISSUE THREAD

**Issue by aghatpande** [AlgoveraAI/generative-art#1]
I’ve found out so far the dataset needs to be in a png format as a zip archive for stylegan2
Also, I had to include a variable "transaction timeout" for the call to the "wallet" function from oceanlib for it to work. 
 Not clear on whether we need additional data to supply examples of things that are noise?
Stylegan2 does seem overkill for cruptopunks.  Simpler GAN code available on GitHub.

**Comment by richardblythman** [comment]
Hi! Thanks for creating the first issue :)

- Yes, as a first step, was thinking we could publish an algorithm for processing the raw CryptoPunks dataset to the format needed for whatever model we choose to use. It should be easier to get a quick and simple algorithm like this working than a training algorithm. I'll create an issue for this. 
- Thanks for letting everyone know about this. It's likely due to an upgrade to ocean.py. Would you be able to try out creating an issue, creating a new branch, fixing the issue and submitting a pull request for this?
- Not sure where they generate the noise in the code. As far as I'm aware the noise is usually fixed, although some artists have found that it is helpful to modify the noise tensor (see the discussion [here](https://hollygrimm.com/geomorphs)).
- Agreed. Now that we decided to train on lo-res images, StyleGAN2 is probably overkill. I created an issue to explore alternatives. If you reviewed some, maybe you could add an analysis under that issue thread?
